spring.application.name=FlightReservationApplication

spring.datasource.url=jdbc:mysql://terraform-20260401061933458900000002.clmkw2ya0ihz.ap-northeast-2.rds.amazonaws.com:3306/flightdb?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Redhat123
frontend.url=http://cbz-frontend-a67f591d.s3-website.ap-northeast-2.amazonaws.com



# Hibernate properties for MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.auto-commit=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.address=0.0.0.0
